
# 服务器端口
server:
  port: 8085


logging:
  level:
    # 设定日志输出级别
    root: info
    hui: debug
  group:
    hui: com.hui
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: log/huiServer.log
  logback:
    rollingpolicy:
      max-file-size: 10KB
      file-name-pattern: log/%d{yyyy-MM}/huiServer.%d{yy-MM-dd}.%i.log
      max-history: 3

# mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  ## 开启mybatisPlus运行日志到控制台
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      # 配置全部表的默认id生成策略
      id-type: auto
      # 配置所有表添加逻辑删除
#      logic-delete-field: deleted   # 所有表添加逻辑删除字段为deleted
#      logic-delete-value: 0         # 所有表的逻辑删除功能中, 未删除状态=0
#      logic-not-delete-value: 1     # 所有表的逻辑删除功能中, 已删除状态=1

    banner: off






